language: node_js

node_js:
- 6

branches:
  only:
  - master

before_install:
- export TZ='Asia/Shanghai'
- openssl aes-256-cbc -K $encrypted_7dd4dae099e2_key -iv $encrypted_7dd4dae099e2_iv
  -in id_rsa.enc -out id_rsa -d
- ls -a
- ls -a ~/.ssh/
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

- git config --global user.name 'Toby @ Travis CI'
- git config --global user.email toby.qin@live.coom
- python @prepare.py

install:
- npm install hexo-cli -g
- npm install

addons:
  ssh_known_hosts: git.coding.net

script:
- hexo clean
- hexo generate

after_success:
- hexo deploy

cache:
  directories:
    - node_modules